-- cadastrar um novo usuario
CREAT OR REPLACE PROCEDURE CADASTRAR_USUARIO(ID NUMBER, USERNAME VARCHAR) IS

BEGIN
    INSERT INTO USUARIO (ID, USERNAME)
        VALUES (ID, USERNAME)
    DBMS_OUTPUT.PUT_LINE('USUARIO ' || USERNAME || ' CADASTRADO COM SUCESSO');
END;

CREATE OR REPLACE PROCEDURE CONTRATAR_DEV (codDEV NUMBER, idJOGO NUMBER, idEMPRESA NUMBER, func VARCHAR2) IS
    new_dev NUMBER;
    cod_empresa NUMBER;
    cod_jogo NUMBER;
BEGIN
    SELECT USUARIO_ID INTO new_dev
    FROM DEV
    WHERE USUARIO_ID = codDEV;

    SELECT ID INTO cod_empresa
    FROM EMPRESA
    WHERE ID = idEMPRESA

    SELECT  

    INSERT INTO DESENVOLVE VALUES (new_dev,idJogo,idEmpresa,func);
    DBMS_OUTPUT.PUT_LINE('DESENVOLVEDOR CONTRATADO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('UM DOS CAMPOS INFORMADOS NÃO EXISTE');
END;
