-- cadastrar um novo usuario
CREAT OR REPLACE PROCEDURE CADASTRAR_USUARIO(ID NUMBER, USERNAME VARCHAR) IS

BEGIN
    INSERT INTO USUARIO (ID, USERNAME)
        VALUES (ID, USERNAME)
    DBMS_OUTPUT.PUT_LINE('USUARIO ' || USERNAME || ' CADASTRADO COM SUCESSO');
END;
