-- cadastrar um novo usuario
CREAT OR REPLACE PROCEDURE CADASTRAR_USUARIO(ID NUMBER, USERNAME VARCHAR) IS

BEGIN
    INSERT INTO USUARIO (ID, USERNAME)
        VALUES (ID, USERNAME)
    DBMS_OUTPUT.PUT_LINE('USUARIO ' || USERNAME || ' CADASTRADO COM SUCESSO');
END;

-- Contrata dev e retorna a quantidade de devs na empresa
CREATE OR REPLACE FUNCTION CONTRATAR_DEV (codDEV NUMBER, idJOGO NUMBER, idEMPRESA NUMBER, func VARCHAR2) RETURN NUMBER IS
    new_dev NUMBER;
    cod_empresa NUMBER;
    cod_jogo NUMBER;
    qtd_dev NUMBER;
BEGIN
    SELECT USUARIO_ID INTO new_dev
    FROM DEV
    WHERE USUARIO_ID = codDEV;

    SELECT ID INTO cod_empresa
    FROM EMPRESA
    WHERE ID = idEMPRESA;

    SELECT ID INTO cod_jogo
    FROM JOGO
    WHERE ID = idJOGO;

    INSERT INTO DESENVOLVE VALUES (new_dev,idJogo,idEmpresa,func);
    DBMS_OUTPUT.PUT_LINE('DESENVOLVEDOR CONTRATADO');
    
    SELECT COUNT(*) INTO qtd_dev
    FROM DEV D INNER JOIN USUARIO U ON (D.USUARIO_ID = U.ID)
    WHERE D.USUARIO_ID IN (
        SELECT USUARIO_ID
        FROM DESENVOLVE
        WHERE EMPRESA_ID = cod_empresa
    );

    RETURN qtd_dev;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('UM DOS CAMPOS INFORMADOS NÃO EXISTE');
        RETURN NULL;
END;


