
--USUARIO: ID (PK), USERNAME 
INSERT INTO USUARIO VALUES ( 1111, 'TBonnep');
INSERT INTO USUARIO VALUES ( 2222, 'MANBR');
INSERT INTO USUARIO VALUES ( 1112, 'RAFAPAZ');


--CONTA: ID (FK de USUARIO), Senha, EMAIL
INSERT INTO CONTA VALUES ( 1111, 'batatadoce', 'tbonnetest42@gmail.com');
INSERT INTO CONTA VALUES ( 2222, 'saopaulohorrivel', 'manbr@cin.ufpe.br');
INSERT INTO CONTA VALUES ( 1112, 'flamengohorrivel', 'rpf@cin.ufpe.br');


--CARTAO: ID (FK de CONTA), NUM, COD, DT_EXP (DATA)
INSERT INTO CARTAO VALUES (1111, 5484701197164657, 919, TO_DATE('13/12/2025','DD/MM/YYYY'));

--PLAYER: ID (FK DE USUARIO)
INSERT INTO PLAYER VALUES (1111);
INSERT INTO PLAYER VALUES (1112);

--DEV: ID (FK de USUARIO)
INSERT INTO DEV VALUES (2222);

--JOGO ID, NOME, DT_LANÇAMENTO, PREÇO
INSERT INTO JOGO VALUES (669,'SUPER IP',TO_DATE('29/05/2023','DD/MM/YYYY'), 15.99);

--DESENVOLVE USUARIO_ID, JOGO_ID, EMPRESA_ID, FUNCAO
-- SOU A FAVOR DE RENOMEAR USUARIO ID PARA DEV ID
INSERT INTO DESENVOLVE VALUES (2222, 669, NULL, 'Desenvolvedor');

--TEM: USUARIO_ID, JOGO_ID
--TBM TROCARIA USUARIO ID PARA PLAYER ID
INSERT INTO TEM VALUES (1111, 669);

--CONQUISTAS: USUARIO ID, JOGO ID, CONQUISTA
INSERT INTO CONQUISTAS VALUES (1111, 669, 'APROVADO!');

--COMENTÁRIO: JOGO ID, USUARIO ID, DATE, ESTRELAS, DESCRICAO
INSERT INTO COMENTARIO VALUES (669, 1111, TO_DATE('13/12/2025','DD/MM/YYYY'), 5, 'EXCELENTE JOGO.');

--AMIGO: ID AMIGO 1, ID AMIGO 2
INSERT INTO AMIGO VALUES (1111, 1112);

--EMPRESA: ID (PK), NOME
INSERT INTO EMPRESA VALUES(0001,'CITI');

--COMPARTILHA: JOGO ID, DEPENDENTE ID, DONO ID
INSERT INTO COMPARTILHA VALUES (669, 1112, 1111);
